### ISSUE TITLE
小 BUG

### ISSUE THREAD

**Issue by GuTiewei** [beecloud/beecloud-rest-api#13]
资源版本路径不起作用，例如：http://apibj.beecloud.cn/1/rest/bill和http://apibj.beecloud.cn/2/rest/bill以及http://apibj.beecloud.cn/gtw/rest/bill 能够访问同样的资源，建议用常量限制版本路径。

**Comment by quietbamboo** [comment]
@josephgao 解决了嘛？

**Comment by josephgao** [comment]
没有解决，需要修改

**Comment by josephgao** [comment]
已解决
