### ISSUE TITLE
支付接口的返回值如何用？

### ISSUE THREAD

**Issue by hustKiwi** [beecloud/beecloud-rest-api#17]
依文档说明调用支付接口 `/1/rest/bill` ，会获得如下数据格式的返回值：
```coffeescript
{
  result_msg: 'OK',
  resultCode: 0,
  errMsg: 'OK:',
  err_detail: '',
  result_code: 0,
  html: '<form id="alipaysubmit" name="alipaysubmit" action="https://mapi.alipay.com/gateway.do?_input_charset=utf-8" method="get"><input type="hidden" name="seller_email" value="admin@google.com"/><input type="hidden" name="subject" value="21. 吉他入门"/><input type="hidden" name="_input_charset" value="utf-8"/><input type="hidden" name="sign" value="faceb960d9d2e1d57b7c9fd6a7915cc8"/><input type="hidden" name="notify_url" value="http://payservice.beecloud.cn/bcpay/aliPayDynamic/c5d1cba1-5e3f-4ba0-941d-9b0a371fe719_f1d1287c-3eeb-41e5-a899-57933bccd8cd.php"/><input type="hidden" name="payment_type" value="1"/><input type="hidden" name="out_trade_no" value="55f8691c598846e06b775305"/><input type="hidden" name="partner" value="2088711322600300"/><input type="hidden" name="service" value="create_direct_pay_by_user"/><input type="hidden" name="total_fee" value="39.0"/><input type="hidden" name="return_url" value="http://127.0.0.1:8889/payment/_hook"/><input type="hidden" name="exter_invoke_ip" value="1.202.65.82"/><input type="hidden" name="sign_type" value="MD5"/><input type="submit" value="确认" style="display:none;"></form><script>document.forms[\'alipaysubmit\'].submit();</script>',
  id: 'f1d1287c-3eeb-41e5-a899-57933bccd8cd',
  url: 'https://mapi.alipay.com/gateway.do?_input_charset=utf-8&seller_email=admin@google.com&subject=21. 吉他入门&_input_charset=utf-8&sign=faceb960d9d2e1d57b7c9fd6a7915cc8&notify_url=http://payservice.beecloud.cn/bcpay/aliPayDynamic/c5d1cba1-5e3f-4ba0-941d-9b0a371fe719_f1d1287c-3eeb-41e5-a899-57933bccd8cd.php&payment_type=1&out_trade_no=55f8691c598846e06b775305&partner=2088711322600300&service=create_direct_pay_by_user&total_fee=39.0&return_url=http://127.0.0.1:8889/payment/_hook&exter_invoke_ip=1.202.65.82&sign_type=MD5'
}
```

### 这里有两个问题：
1. 请问这个返回值中 `html` 和 `url` 有什么区别？看了下，最后的结果都是向 `Alipay Server` 发带支付参数的get请求。
2. 这个返回值我是通过demo中提供的 `App Id 和 Secret` 调用API获得的，但访问返回结构中的 `url` ，支付宝报错，提示：

> 调试错误，请回到请求来源地，重新发起请求。
错误代码 ILLEGAL_PARTNER

请问这是什么原因？

**Comment by hustKiwi** [comment]
@quietbamboo @Danzeer

**Comment by Danzeer** [comment]
1. 不同渠道的支付网关的访问方式不同（GET or POST）
    实现支付跳转有俩种方式：A.GET方式访问url，在url里带有uri参数（比如ALI）
                                               B.用POST方式访问url（比如 union）,参数在post的http body中

    对于A方式返回的html（form表单+js调用form submit）和 url （js 通过loation.href）一致
    但是B方式则只能通过html

**Comment by Danzeer** [comment]
2 由于支付宝不允许跨域调用支付功能，在非beecloud域名下发起支付会被加入黑名单，所以我们不再提供真实的参数，请替换为自己的参数后测试

**Comment by Danzeer** [comment]
@hustKiwi little problem？如果你想用ajax获取些支付form参数，js里自己做form submit貌似目前好做（1jsonp目前不支持 2server获取到html可能需要你自己匹配出各个参数）

**Comment by hustKiwi** [comment]
@Danzeer 多谢回复，明白了。
没关系，我没有通过ajax直接提交支付数据，通过前端表单提交后由我自己这边的 `node server` 向咱们 `rest api server` 发起请求，等于做了一个proxy，不存在跨域问题。

另外还有一个问题提出来讨论下：
`/1/rest/bill` 接口会返回唯一标示 `id ` 字段，这个字段需要开发者保存起来，作为查查询支付状态 `/1/rest/bill/{id}` 时用吧？

这样问题也不大，但会涉及改动已有表结构和逻辑。为什么不用 `app_id + 用户bill_id` 做索引呢？

另外复议，我看到提供了 `/1/rest/bills` 接口，但这个接口通过  `app_id + 用户bill_id` 查出来的会是一个list，一般的需求会是这样吗？我理解难道不是每个用户bill_id只会对应一个订单吗？

**Comment by Danzeer** [comment]
id是为了拓展用的
bills接口是条件查询
bill/{id}是id查询，因为在使用过程中，用户总是有可能重复的传bill_no（注意这是用户自定义的，不是bill_id），或者同一个订单第一次未支付成功，想重复支付，所以bills返回的是list格式的。

**Comment by hustKiwi** [comment]
多谢解释。
