### ISSUE TITLE
err_detail大概会返回什么值？

### ISSUE THREAD

**Issue by hustKiwi** [beecloud/beecloud-rest-api#18]
从文档中看到，当 `result_code` 不为0时，会返回错误信息 `err_detail` 。那么请问这个 `err_detail` 大概会是什么样的信息？是针对开发者的堆栈调试信息，还是对应 `result_msg` 的解释。

问这个问题主要我想了解下这个错误信息是否应该展示给用户，还是我作为异常记录在供开发者排查的 error log 中更合适？

**Comment by hustKiwi** [comment]
@quietbamboo @Danzeer

**Comment by Danzeer** [comment]
result_code 不为零，会返回err_msg, 主要用来提示开发者哪哪传错了，或者BeeCloud上xxx没有设置；
err_detail 是进一步详细补充，比如微信返回的原始信息等

这个错误信息没有展示给支付用户的必要，记录在error中更好，基本开发时才会用到

**Comment by hustKiwi** [comment]
Thanks
