### ISSUE TITLE
为何不统一API的传参方式？

### ISSUE THREAD

**Issue by hustKiwi** [beecloud/beecloud-rest-api#19]
看了下，现在 `POST` 请求的API都是传JSON MAP，但 `GET` 请求却是多了一层，要求 `以para={}的方式请求`。为何在API接口的设计上要强求这样的区别？这样做，是不是反而增加了不必要的解释和复杂性呢？

另外我看了下官方实现的sdk，发现在sdk层面就对API传参做了验证，这样做是否有必要？在我看来，参数验证放到 `REST API Server` 去做最合适，这样可保证验证验证逻辑即报错信息的一致性，也方便SDK的开发维护。

举例说明，比如 `paython sdk` 对 `refund_no` 做了[合法类型及可能取值范围的强验证](https://github.com/beecloud/beecloud-python/blob/master/sdk/bc_api.py#L169-L170)，而 `php sdk` 只对 `refund_no` 简单[是否存在的弱验证](https://github.com/beecloud/beecloud-php/blob/master/sdk/src/rest/api.php#L148-L149)，连报错信息都会有所区别。更何况，如果之后 `REST API Server` 端升级了对应接口参数类型，导致旧版本的sdk还可能因为验证逻辑的瑕疵不能使用，得不偿失。

**Comment by Danzeer** [comment]
1.GET属于uri传参，使用的框架要求必须是a＝b的形式， 复杂性被sdk封装后基本转移到了sdk的参数复杂性上了，毕竟直接去调用的人是少数

2.API服务层对所有参数已经做了最严格的检查，各个sdk只是确保部分层面的验证，目的是让用户一上手写的代码基本不会错减少客服工作量；配合demo样例代码，基本照着写也不会错太多；此外各个语言强弱类型不同不好判断(比如用js去判断uuid之类的)，用正则去做检查又觉得牛刀杀鸡了（一个字懒）

3. API的升级我们一定是考虑到兼容性的，一般不会更改现有参数类型，SDK也会保证及时更新；特别大影响的则会去修改版本号1这个前缀前缀，目前还没有特别大的架构更改

**Comment by josephgao** [comment]
我补充一下，不论GET还是POST我们想传的都是json，所以GET也传了一个统一的Map.

第二个问题其实是我们没有做好，这里有三点要做的，第一点是Rest api server也做了所有的参数检查，第二点是sdk也应该做必要的检查，第三点是sdk的检查逻辑和返回结果应该统一，前两点我们做了，但是第三点没有做到，这个是我们的瑕疵，虽然不影响使用（因为在server端做检查了），但是不够完美；sdk做参数检查的目的是减少网络通信：一些sdk已经能判断必定失败的请求就没必要发了。

RESTApi的升级我们目前是这样设计的，升级肯定会带来一些逻辑的冲突，但是我们要做到旧版本的sdk仍旧能够使用，只不过新版本的sdk会有一些新特性，基于这一点我们会保留1-2个老的RESTApi存在，直至到更多大版本的更新，我们会舍弃最老的API，但我们会给1-3个月的缓冲时间，因为第三方支付渠道变更或是其他原因这是不可避免的。

非常感谢您的建议尤其是第二点，是我们需要改正的地方，我们会尽快统一所有sdk的检查逻辑，谢谢！

**Comment by josephgao** [comment]
我补充一下，不论GET还是POST我们想传的都是json，所以GET也传了一个统一的Map.

第二个问题其实是我们没有做好，这里有三点要做的，第一点是Rest api server也做了所有的参数检查，第二点是sdk也应该做必要的检查，第三点是sdk的检查逻辑和返回结果应该统一，前两点我们做了，但是第三点没有做到，这个是我们的瑕疵，虽然不影响使用（因为在server端做检查了），但是不够完美；sdk做参数检查的目的是减少网络通信：一些sdk已经能判断必定失败的请求就没必要发了。

RESTApi的升级我们目前是这样设计的，升级肯定会带来一些逻辑的冲突，但是我们要做到旧版本的sdk仍旧能够使用，只不过新版本的sdk会有一些新特性，基于这一点我们会保留1-2个老的RESTApi存在，直至到更多大版本的更新，我们会舍弃最老的API，但我们会给1-3个月的缓冲时间，因为第三方支付渠道变更或是其他原因这是不可避免的。

非常感谢您的建议尤其是第二点，是我们需要改正的地方，我们会尽快统一所有sdk的检查逻辑，谢谢！

**Comment by hustKiwi** [comment]
多谢回复。关于sdk做参数检查的目的是减少网络通信我持保留意见。对于支付API，传错参数类型的情况我估计只在开发调试时才会碰到。正式产品中，对于支付这么重要的功能，默认肯定是测试过按要求传的，因此不太可能频繁遇到传参错误的问题。

**Comment by lacusrinz** [comment]
我赞同这种说法，上线的产品不太可能频繁遇到参数错误，SDK不做参数检查更有利于减少服务端升级而SDK没有及时跟进导致的问题

**Comment by Danzeer** [comment]
debug & release 模式，debug才做验证；默认是debug的，调试完成设置为release

**Comment by josephgao** [comment]
嗯，sdk参数检查这里我觉得可以接受@hustKiwi的意见，我们会把这个放在近期的todo里面；另外也要确保server端的check cover所有的情况

**Comment by josephgao** [comment]
已逐步将server端的check cover到能想到的情况，sdk可以逐步去掉参数检查的部分。
