### ISSUE TITLE
知乎上反馈的API相关问题

### ISSUE THREAD

**Issue by hustKiwi** [beecloud/beecloud-rest-api#20]
其他开发者在之后上反馈的问题如下：http://www.zhihu.com/question/31237376
>
我也在做公司内部支付中心，以下纯属个人观点；
>
详细看了两家的API， 抛开安全不讲，发现部分问题：
1. 对于回调接口都未做参数签名
存在的风险： 用户下了单但没付款， 知道回掉接口， 直接mock一个支付成功请求， 商户以为已支付成功， 结果钱没收到货发出去了。
2. 回调均未考虑第三方处理失败的情况， 给出关键的提示， 要知道支付宝和微信针对不同的支付场景可是定义了数十个错误码和异常码。
3. beecloud参数不统一， 驼峰命名和蛇形命名交叉使用，很是迷惑， 还把第三方的所有参数封装在messageDetail中， 其实商户估计只关心这笔订单的主体内容和交易（付款和退款）是否成功吧。
4. ping++ 回调参数给了一大堆示例， 但对字段的解释只字不提， 难道要开发者去猜？
>
个人对接口的理解：
第一层： 能用，不能容错， 不能给出准确的提示。
第二层： 实用，能容错，能给出准确的提示。
第三层： 好用，在第二层的基础上增加统一的规范，完善并标准的文档， 每一种场景标准的测试用例， 最后做到开箱即用。
>
接口并发问题暂不在此罗列。

我个人理解是：
1. 没有问题，有通过key, secret和timestamp做md5签名，实现时在回调接口验证下应该不存在问题
**2. 不清楚对方是如何验证的，如果这里未考虑第三方接口失败情况，应该是严重bug。请帮忙确认。**
3. 确实存在这个问题，API是 `snake_case` ，webhook是 `camelCase`。

另外，关于webhook的 `messageDetail` ，我也有一些疑问。给出原始信息没有问题，但在我实现支付时，并不完全依赖回调去确认订单是否成功，有时也会主动调用 `订单查询接口 /1/rest/bill/{id}` 去check支付状态，但这个查询接口并没有返回类似webhook中 `messageDetail` 的原始信息结构，这让我在设计我订单相关的存储结构时也比较困惑，不知道该如何存储第三方信息以防特殊情况时对比、使用。因此建议订单查询接口也一并反馈类似webhook的 `messageDetail` ，维持数据结构的一致性。

**Comment by quietbamboo** [comment]
非常好的评论，我们商量下如何重构，改进接口，这个issue留着持续update

**Comment by quietbamboo** [comment]
1 你的理解正确，通过sign来验证签名没有问题。
2 这是基于我们的设计，因为之前有的客户与我们联系说没必要给他们发失败的或者还没成功的webhook；不过我反思了一下，如果有的客户需要等着这些失败的event来做设计，那么我们这一层的过滤就让他没办法来实现了。所以我们会修改一下webhook，里面加上各种错误代码，统一之后返回给用户。
3 属于历史遗留问题，我们会逐步过渡到snake_case的模式。

关于messageDetail，未来的查询接口里也会有，不过考虑到messageDetail比较大，我们考虑在查询的时候加一个开关，默认没有messageDetail，只有传这个开关是true的时候，才传messageDetail，这样从节约带宽，提高响应速度的角度而言是有帮助的。

**Comment by josephgao** [comment]
3.问题请跟踪https://github.com/beecloud/beecloud-webhook/issues/4
2问题我们会评估一下，如果确实是有一些错误码或错误信息是用户需要的，我们会考虑修改
查询的时候messageDetail，我们也会保存并按照@quietbamboo说的那种方式返回给用户

**Comment by josephgao** [comment]
问题已解决， 
1.无法伪造异步通知
2.目前客户的需求是过滤掉失败的异步通知
3.现版本api已更新使用snace_case
4.已添加message_detail里主要字段说明

**Comment by hustKiwi** [comment]
:+1:
