### ISSUE TITLE
文档略长了，可以分不同的md

### ISSUE THREAD

**Issue by Danzeer** [beecloud/beecloud-rest-api#24]

**Comment by Danzeer** [comment]
1. api 基本情况概述和列表
2. 发起支付
3. 查询支付，按照id查询支付
4. 发起退款/预退款， 审核退款，退款状态更新
5. 批量打款
。。。。。

**Comment by quietbamboo** [comment]
不建议切不同md  因为同一个md可以很轻易地转成一整个pdf文件

**Comment by josephgao** [comment]
暂时按照产品的维度来切分文档
